[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./bin/rails server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheckPath]]
path = "/"

[[deploy.healthcheckTimeout]]
timeout = 300
